# Autogenerated wrapper script for XicTools_jll for x86_64-linux-gnu-cxx11
export admsXml, busgen, capgen, cubegen, fastcap, fasthenry, fcpp, lstpack, lstunpack, mmjco, mrouter, multidec, pipedgen, printtoraw, proc2mod, pyragen, vl, wrdecode, wrencode, wrspice, wrspiced, xic, zbuf

using Libtiff_jll
using libpng_jll
using JpegTurbo_jll
using GSL_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("XicTools")
JLLWrappers.@declare_executable_product(admsXml)
JLLWrappers.@declare_executable_product(busgen)
JLLWrappers.@declare_executable_product(capgen)
JLLWrappers.@declare_executable_product(cubegen)
JLLWrappers.@declare_executable_product(fastcap)
JLLWrappers.@declare_executable_product(fasthenry)
JLLWrappers.@declare_executable_product(fcpp)
JLLWrappers.@declare_executable_product(lstpack)
JLLWrappers.@declare_executable_product(lstunpack)
JLLWrappers.@declare_executable_product(mmjco)
JLLWrappers.@declare_executable_product(mrouter)
JLLWrappers.@declare_executable_product(multidec)
JLLWrappers.@declare_executable_product(pipedgen)
JLLWrappers.@declare_executable_product(printtoraw)
JLLWrappers.@declare_executable_product(proc2mod)
JLLWrappers.@declare_executable_product(pyragen)
JLLWrappers.@declare_executable_product(vl)
JLLWrappers.@declare_executable_product(wrdecode)
JLLWrappers.@declare_executable_product(wrencode)
JLLWrappers.@declare_executable_product(wrspice)
JLLWrappers.@declare_executable_product(wrspiced)
JLLWrappers.@declare_executable_product(xic)
JLLWrappers.@declare_executable_product(zbuf)
function __init__()
    JLLWrappers.@generate_init_header(Libtiff_jll, libpng_jll, JpegTurbo_jll, GSL_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        admsXml,
        "bin/admsXml",
    )

    JLLWrappers.@init_executable_product(
        busgen,
        "bin/busgen",
    )

    JLLWrappers.@init_executable_product(
        capgen,
        "bin/capgen",
    )

    JLLWrappers.@init_executable_product(
        cubegen,
        "bin/cubegen",
    )

    JLLWrappers.@init_executable_product(
        fastcap,
        "bin/fastcap",
    )

    JLLWrappers.@init_executable_product(
        fasthenry,
        "bin/fasthenry",
    )

    JLLWrappers.@init_executable_product(
        fcpp,
        "bin/fcpp",
    )

    JLLWrappers.@init_executable_product(
        lstpack,
        "bin/lstpack",
    )

    JLLWrappers.@init_executable_product(
        lstunpack,
        "bin/lstunpack",
    )

    JLLWrappers.@init_executable_product(
        mmjco,
        "bin/mmjco",
    )

    JLLWrappers.@init_executable_product(
        mrouter,
        "bin/mrouter",
    )

    JLLWrappers.@init_executable_product(
        multidec,
        "bin/multidec",
    )

    JLLWrappers.@init_executable_product(
        pipedgen,
        "bin/pipedgen",
    )

    JLLWrappers.@init_executable_product(
        printtoraw,
        "bin/printtoraw",
    )

    JLLWrappers.@init_executable_product(
        proc2mod,
        "bin/proc2mod",
    )

    JLLWrappers.@init_executable_product(
        pyragen,
        "bin/pyragen",
    )

    JLLWrappers.@init_executable_product(
        vl,
        "bin/vl",
    )

    JLLWrappers.@init_executable_product(
        wrdecode,
        "bin/wrdecode",
    )

    JLLWrappers.@init_executable_product(
        wrencode,
        "bin/wrencode",
    )

    JLLWrappers.@init_executable_product(
        wrspice,
        "bin/wrspice",
    )

    JLLWrappers.@init_executable_product(
        wrspiced,
        "bin/wrspiced",
    )

    JLLWrappers.@init_executable_product(
        xic,
        "bin/xic",
    )

    JLLWrappers.@init_executable_product(
        zbuf,
        "bin/zbuf",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
